server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://sdcnppuat01.chowsangsang.com:3306/expressdv?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: sys_dv
#    password: sys_dv
    url: jdbc:mysql://192.168.3.240:3306/spring_cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cloud.entities

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    #    显示主机名
    instance-id: payment8001
    #    显示IP
    prefer-ip-address: true

